### ISSUE TITLE
Looking at merging changes from @DerpyChap

### ISSUE THREAD

**Issue by stuaxo** [hugovk/winamp#2]
Apologies for putting this here, but I can't report a bug to the repo by @DerpyChap

@DerpyChap - I'm trying to understand the changes you made, 

How is FilePath meant to be used ?

I guess the ```import win32con``` is just there by accident.

**Comment by DerpyChap** [comment]
I haven't worked on it in nearly a year and my memory is a little hazy, but I *think* `FilePath` was a function that either returned the file path of the current playlist OR the current song. I can't remember if it even worked or not. As for the import, I have no clue. Possibly a leftover from me experimenting with various things.

**Comment by stuaxo** [comment]
Cheers :)
